name: comunic_app
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  localization: ^2.1.0
  dio: ^5.1.1
  flutter_modular: ^5.0.3
  #flutter_triple: ^2.0.0
  flutter_triple: ^1.2.7+4
  flutter_svg_provider: ^1.0.3
  onboarding: ^3.1.0
  mobx: ^2.1.4
  mask_text_input_formatter: ^2.4.0
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/